### ISSUE TITLE
`tfvars` doesn't match required variables`

### ISSUE THREAD

**Issue by timfallmk** [sethvargo/terraform-workshop-atlas#2]
It looks like there's a minor difference in the `terraform.tfvars` file at the root level. I think `atlas_consul_token` should be `atlas_token`.

**Comment by sethvargo** [comment]
@timfallmk fixed, but don't use that tfvars file (it probably shouldn't even be checked in). Run ./scripts/package and it will generate an empty one for you (as well as remove all the helper files).

**Comment by sethvargo** [comment]
@timfallmk fixed, but don't use that tfvars file (it probably shouldn't even be checked in). Run ./scripts/package and it will generate an empty one for you (as well as remove all the helper files).
